haar_modulus.svg:	DWT_filters_study.ipynb
	jupyter nbconvert --to notebook --execute DWT_filters_study.ipynb
SVGs += haar_modulus.svg
TMPs += haar_modulus.pdf

haar_phase.svg:	DWT_filters_study.ipynb
	jupyter nbconvert --to notebook --execute DWT_filters_study.ipynb
SVGs += haar_phase.svg
TMPs += haar_phase.pdf

db5_modulus.svg:	DWT_filters_study.ipynb
	jupyter nbconvert --to notebook --execute DWT_filters_study.ipynb
SVGs += db5_modulus.svg
TMPs += db5_modulus.pdf

db5_phase.svg:	DWT_filters_study.ipynb
	jupyter nbconvert --to notebook --execute DWT_filters_study.ipynb
SVGs += db5_phase.svg
TMPs += db5_phase.pdf

LL3.png:	DWT_basis.ipynb
	jupyter nbconvert --to notebook --execute DWT_basis.ipynb
#PNGs += LL3.png
TARs += LL3.png
TMPs += LL3.png

dwt_lena.png:	DWT_lena.ipynb
	jupyter nbconvert --to notebook --execute DWT_lena.ipynb
PNGs += dwt_lena.png
#SVGs += dwt_lena.svg
TMPs += dwt_lena.pdf

#DWT_scaled.pdf:	DWT.pdf
#	gs -sDEVICE=pdfwrite -dDEVICEWIDTHPOINTS=100 -dPDFSETTINGS=/default -dNOPAUSE -dQUIET -dBATCH -sOutputFile=DWT_scaled.pdf DWT.pdf
#PDFs += DWT_scaled.pdf

#SVGs += DWT_scaled.svg

include $(HOME)/Makefile_templates/Makefile

